## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/api"
  to = "https://benius.herokuapp.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/uploads"
  to = "https://benius-admin.s3.ap-south-1.amazonaws.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"