[[redirects]]
  from = "/api/*"
  to = "https://benius.herokuapp.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/uploads/*"
  to = "https://benius-admin.s3.ap-south-1.amazonaws.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
