[[redirects]]
	from = "/api/*"
	to = "https://benius.herokuapp.com"
	status = 200
	force = true

[[redirects]]
	from = "/uploads/*"
	to = "https://benius-admin.s3.ap-south-1.amazonaws.com"
	status = 200
	force = true
